### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by zhuchenyu666** [clinicalml/co-llm#10]
small error in collm/dataset/scoring.py/407line:
           labels = [torch.LongTensor(instance) for instance in examples["input_ids"]] 
It should be labels not input_ids.

**Comment by lolipopshock** [comment]
This is not an error but maybe a bit of confusion:

1. in the function [`score_dataset_items_with_model`](https://github.com/clinicalml/co-llm/blob/d83ab8cf19ceb49c7814383a897089e51cdeebfe/collm/dataset/scoring.py#L309), it does not actually change the `labels` (see line 470 to 473; the labels are not added to the data). 
2. we need to get the unmodified labels (the `labels` in `example` is modified because of `-100` in the reformatting stage, e.g., see [this line](https://github.com/clinicalml/co-llm/blob/d83ab8cf19ceb49c7814383a897089e51cdeebfe/collm/dataset/scoring.py#L378)) to compute the `reference_log_probs`.
