### ISSUE TITLE
assert in scoring.py

### ISSUE THREAD

**Issue by zhuchenyu666** [clinicalml/co-llm#11]
why do you assert in line475 in scoring.py:

```
        for example in data_dict: 
              assert len(example["reference_log_probs"]) == len(example["input_ids"]) - 1
```
I think reference_log_probs filters out padding tokens, while input_ids does not, so their lengths must be very different.
Can you explain this?

**Comment by lolipopshock** [comment]
No we do not add padding in `scoring.py` but we add it during the training time: https://github.com/clinicalml/co-llm/blob/d83ab8cf19ceb49c7814383a897089e51cdeebfe/collm/training/deferral_training_tools.py#L258

(The padding code in `scoring.py` actually doesn't take effect since for each time the batch size is only 1, which means it won't add the padding regardless.)
